#!/bin/bash

#-------------------------------------------
# the path of flame graph scripts, default is "/opt/FlameGraph"
# https://github.com/brendangregg/FlameGraph
#
flame_graph_path="/opt/FlameGraph/"

#-------------------------------------------
function folded_data_to_frame_graph ( )
{
	local folded_data=$1
	local svg="${folded_data}.svg"

	echo flaming folded
	cat "${folded_data}" \
		| ${flame_graph_path}/flamegraph.pl --title="${svg}" \
		> "${svg}"

	echo flaming done
}

#-------------------------------------------
function folded_data_to_diff_frame_graph ( )
{
	local folded_before=$1
	local folded_after=$2
	local keep_intermediate=$3
	local option=""
	local diff_flame_before="${folded_before}.base1.svg"
	local diff_flame_after="${folded_after}.base2.svg"

	local diff_folded_before="${folded_before}.diff.folded"
	local diff_folded_after="${folded_after}.diff.folded"

	echo diff flaming folded
	${flame_graph_path}/difffolded.pl ${option}  "${folded_before}"  "${folded_after}" \
		> "${diff_folded_after}"
	${flame_graph_path}/flamegraph.pl --title="${diff_flame_after}" \
		< "${diff_folded_after}" \
		> "${diff_flame_after}"
	${flame_graph_path}/difffolded.pl ${option}  "${folded_after}"  "${folded_before}" \
		> "${diff_folded_before}"
	${flame_graph_path}/flamegraph.pl --title="${diff_flame_before}" --negate \
		< "${diff_folded_before}" \
		> "${diff_flame_before}"

	# clean
	if [ $keep_intermediate -eq 0 ]; then
		rm -f  "${diff_folded_before}"
		rm -f  "${diff_folded_after}"
	fi

	echo diff flaming done
}


#-------------------------------------------
function perf_data_to_frame_graph ( )
{
	local perf_data=$1
	local svg="${perf_data}.svg"

	echo flaming perf data
	perf script -i "${perf_data}" \
		| ${flame_graph_path}/stackcollapse-perf.pl \
		| ${flame_graph_path}/flamegraph.pl --title="${svg}" \
		> "${svg}"

	echo flaming done
}

#-------------------------------------------
function perf_data_to_diff_frame_graph ( )
{
	local perf_data_before=$1
	local perf_data_after=$2
	local keep_intermediate=$3
	local option=""
	local diff_flame_before="${perf_data_before}.base1.svg"
	local diff_flame_after="${perf_data_after}.base2.svg"

	local folded_before="${perf_data_before}.folded"
	local folded_after="${perf_data_after}.folded"
	local diff_folded_before="${perf_data_before}.diff.folded"
	local diff_folded_after="${perf_data_after}.diff.folded"

	echo diff flaming ps
	perf script -i "${perf_data_before}" \
		| ${flame_graph_path}/stackcollapse-perf.pl \
		> "${folded_before}"
	perf script -i "${perf_data_after}" \
		| ${flame_graph_path}/stackcollapse-perf.pl \
		> "${folded_after}"

	echo diff flaming df
	${flame_graph_path}/difffolded.pl ${option}  "${folded_before}"  "${folded_after}" \
		> "${diff_folded_after}"
	${flame_graph_path}/flamegraph.pl --title="${diff_flame_after}" \
		< "${diff_folded_after}" \
		> "${diff_flame_after}"

	${flame_graph_path}/difffolded.pl ${option}  "${folded_after}"  "${folded_before}" \
		> "${diff_folded_before}"
	${flame_graph_path}/flamegraph.pl --title="${diff_flame_before}" --negate \
		< "${diff_folded_before}" \
		> "${diff_flame_before}"

	# clean
	if [ $keep_intermediate -eq 0 ]; then
		rm -f  "${folded_before}"
		rm -f  "${folded_after}"
		rm -f  "${diff_folded_before}"
		rm -f  "${diff_folded_after}"
	fi

	echo diff flaming done
}

#-------------------------------------------
function usage_show ( )
{
	echo "create flame graph from <perf.data>"
	echo "    flame <perf.data>"
	echo "create diff flame graph from <perf.data>s"
	echo "    flame -d <perf.data.before> <perf.data.after>"
	echo "create flame graph from <folded.data> directly"
	echo "    flame -f <folded.data>"
	echo "create diff flame graph from <folded.data>s"
	echo "    flame -fd <folded.data.before> <folded.data.after>"
	echo "-k to keep the intermediates"
	echo "-h to show this"
}

#-------------------------------------------
function main ( )
{
	local diff_mode=0
	local folded_mode=0
	local keep_intermediate=0

	while getopts :dfkh FLAG; do
		case $FLAG in
			d)  #set option "d"
				local diff_mode=1
				;;
			f)  #set option "f"
				local folded_mode=1
				;;
			k)  #set option "k"
				local keep_intermediate=1
				;;
			h)  #set option "h"
				usage_show
				exit 1
				;;
			\?) #unrecognized option - show help
				usage_show
				exit 1
				;;
		esac
	done
	# the residual arguments
	shift $((OPTIND-1))
	# echo $@

	if [ "${folded_mode}" -eq 1 ]; then
		if [ "${diff_mode}" -eq 1 ]; then
			folded_data_to_diff_frame_graph $@ ${keep_intermediate}
		else
			folded_data_to_frame_graph $@
		fi
	elif [ "${diff_mode}" -eq 1 ]; then
		perf_data_to_diff_frame_graph $@ ${keep_intermediate}
	else
		perf_data_to_frame_graph $@
	fi
}

#-------------------------------------------
main $*
